<|"SourceVault_anonymize.wl" -> {"$SourceVaultAnonymizeAllowVolatileKeys",
   "$SourceVaultAnonymizeCanonicalizationVersion",
   "$SourceVaultAnonymizeEngineVersion",
   "$SourceVaultAnonymizeFingerprintPinPath",
   "$SourceVaultAnonymizeIdentityKeyRef", "$SourceVaultAnonymizeKeyId",
   "$SourceVaultAnonymizeLineageKeyRef",
   "$SourceVaultAnonymizeLineageSchemaVersion",
   "$SourceVaultAnonymizeTenantID", "SourceVaultAnonymizationPlan",
   "SourceVaultAnonymizeBuildLineageManifest", "SourceVaultValidateLineage",
   "SourceVaultRequestDeclassification", "SourceVaultApproveDeclassification",
   "SourceVaultVerifyDeclassificationGrant",
   "SourceVaultConsumeDeclassificationGrantUse",
   "SourceVaultResolveReleaseHandle", "SourceVaultRevokeReleaseHandle",
   "SourceVaultRotateReleaseHandle",
   "SourceVaultAnonymizePseudonymMapId",
   "SourceVaultAnonymizeAssignSubjectTokens",
   "SourceVaultAnonymizePseudonymMap",
   "SourceVaultAnonymizeVerifyKeyFingerprints",
   "SourceVaultAnonymizeCanonicalDigest",
   "SourceVaultAnonymizeCanonicalEncode",
   "SourceVaultAnonymizeDerivedUnitID", "SourceVaultAnonymizeEntityID",
   "SourceVaultAnonymizeGenerateReleaseHandle",
   "SourceVaultAnonymizeGenerateToken",
   "SourceVaultAnonymizeInitializeKeys", "SourceVaultAnonymizeKeyStatus",
   "SourceVaultAnonymizeReleaseHandleValidQ",
   "SourceVaultAnonymizeSourceObjectID", "SourceVaultAnonymizeSourceUnitID",
   "SourceVaultAnonymizeTokenValidQ"},
 "SourceVault_adjudication.wl" -> {"SourceVaultAddCandidate",
   "SourceVaultAwaitDecisionJob", "SourceVaultDecideCase", 
   "SourceVaultDecisionCase", "SourceVaultDecisionJobResult", 
   "SourceVaultDecisionJobStatus", "SourceVaultEvaluateClaims", 
   "SourceVaultMakeLLMProposer", "SourceVaultMakeLLMVerifier", 
   "SourceVaultOpenDecisionCase", "SourceVaultRunMultiModelDecision", 
   "SourceVaultSubmitMultiModelDecision"}, "SourceVault_anomaly.wl" -> 
  {"SourceVaultActivateCaneBaseline", 
   "SourceVaultAdjudicateAnomalyHypothesis", "SourceVaultAnomalyInitialize", 
   "SourceVaultAnomalyStatus", "SourceVaultAnomalyWorkflowProfile", 
   "SourceVaultCaneActiveBaseline", "SourceVaultCaneAnomalyScheduleTick", 
   "SourceVaultCaneAnomalyWorkflowRuns", "SourceVaultCaneBaselineCandidates", 
   "SourceVaultCaneDiagnosticsProbe", "SourceVaultCaneSensitiveDoctor", 
   "SourceVaultClassifyLineageDependence", 
   "SourceVaultCollectCaneAnomalyStreams", "SourceVaultCorrelateAnomalies", 
   "SourceVaultDetectStreamAnomalies", 
   "SourceVaultGenerateCaneBaselineCandidate", 
   "SourceVaultProposeAnomalyProfileChange", 
   "SourceVaultRegisterCaneAnomalySchedule", 
   "SourceVaultRegisterCaneDiagnostics", "SourceVaultRunCaneAnomalyWorkflow", 
   "SourceVaultSetAnomalyWorkflowProfile", 
   "SourceVaultValidateCaneBaseline"}, "SourceVault_autotrigger.wl" -> 
  {"SourceVaultAutoTriggerCapability", 
   "SourceVaultAutoTriggerConditionMatch", 
   "SourceVaultAutoTriggerConsumePermit", 
   "SourceVaultAutoTriggerDiagnosticsGate", 
   "SourceVaultAutoTriggerDispatchAsync", 
   "SourceVaultAutoTriggerDispatchCatalogRuns", 
   "SourceVaultAutoTriggerDispatchJobs", 
   "SourceVaultAutoTriggerDispatchWorkflows", 
   "SourceVaultAutoTriggerEvaluateTrigger", "SourceVaultAutoTriggerExpiredQ", 
   "SourceVaultAutoTriggerForTarget", 
   "SourceVaultAutoTriggerHeadlessDispatchTick", 
   "SourceVaultAutoTriggerJobQueue", 
   "SourceVaultAutoTriggerKnownMachineTags", 
   "SourceVaultAutoTriggerListData", "SourceVaultAutoTriggerMintPermit", 
   "SourceVaultAutoTriggerNextFire", "SourceVaultAutoTriggerPanel", 
   "SourceVaultAutoTriggerPoll", "SourceVaultAutoTriggerPromptLLM", 
   "SourceVaultAutoTriggerPublishCatalogRuns", 
   "SourceVaultAutoTriggerRunHistory", "SourceVaultAutoTriggerRunningJobs", 
   "SourceVaultAutoTriggerRunningWorkflows", 
   "SourceVaultAutoTriggerScheduleMatch", 
   "SourceVaultAutoTriggerSchedulerStatus", 
   "SourceVaultAutoTriggerSourceIdResolver", 
   "SourceVaultAutoTriggerSourcesURIResolver", 
   "SourceVaultAutoTriggerSpecHash", "SourceVaultAutoTriggerStartScheduler", 
   "SourceVaultAutoTriggerStatus", "SourceVaultAutoTriggerStatusCell", 
   "SourceVaultAutoTriggerStopScheduler", "SourceVaultAutoTriggerTick", 
   "SourceVaultAutoTriggerVerifyPermit", 
   "SourceVaultAutoTriggerWatchRemoteRun", 
   "SourceVaultAutoTriggerWorkflowResolver", 
   "SourceVaultDisableHeadlessDispatch", "SourceVaultEnableHeadlessDispatch", 
   "SourceVaultEnqueueWorkflowRun", "SourceVaultGetAutoTrigger", 
   "SourceVaultHeadlessDispatchEnabledQ", "SourceVaultListAutoTriggers", 
   "SourceVaultNewAutoTriggerId", "SourceVaultParseAutoTriggerPrompt", 
   "SourceVaultRegisterAutoTrigger", "SourceVaultRemoteWorkflowResult", 
   "SourceVaultStartWorkflowForAutoTrigger", 
   "SourceVaultValidateAutoTrigger", "$SourceVaultAutoTriggerEnforcePermit", 
   "$SourceVaultAutoTriggerPermitKeyRef", 
   "$SourceVaultAutoTriggerPermitStore", "$SourceVaultHeadlessDispatch", 
   "$SourceVaultHeadlessDispatchIntervalSeconds"}, 
 "SourceVault_capbroker.wl" -> {"SourceVaultApplyBoundaryObservation", 
   "SourceVaultBoundaryObservationConfig", 
   "SourceVaultCapabilityLeaseLedger", "SourceVaultCapBrokerInitialize", 
   "SourceVaultConsumeCapabilityLease", "SourceVaultLLMBoundaryActiveQ", 
   "SourceVaultLLMBoundaryGate", "SourceVaultLLMBoundaryGateRefusedQ", 
   "SourceVaultLLMBoundarySelfGateRefusedQ", 
   "SourceVaultLLMBoundaryShadowCheck", "SourceVaultLLMBoundaryShadowStats", 
   "SourceVaultLLMEntrypointInventory", "SourceVaultPrepareLLMInput", 
   "SourceVaultPruneCapBroker", "SourceVaultRedeemExecutionTicket", 
   "SourceVaultRegisterLLMEntrypoint", "SourceVaultRequestCapabilityLease", 
   "SourceVaultRevokeCapabilityLeases", "SourceVaultSetBoundaryObservation", 
   "SourceVaultVerifyCapabilityLease", "SourceVaultVerifyPreparedRequest", 
   "$SourceVaultLLMBoundaryEnforceList", "$SourceVaultLLMBoundaryMode", 
   "$SourceVaultLLMBoundaryShadow"}, "SourceVault_cognition.wl" -> 
  {"SourceVaultActionRiskClassify", "SourceVaultAssistanceRecordOutcome", 
   "SourceVaultAssistOwnerInput", "SourceVaultCognitionAppendEvent", 
   "SourceVaultCognitionCompareView", "SourceVaultCognitionErase", 
   "SourceVaultCognitionEvents", "SourceVaultCognitionInitialize", 
   "SourceVaultCognitionPruneExpired", "SourceVaultCognitionSetEnabled", 
   "SourceVaultCognitionStatus", "SourceVaultCognitionSubjects", 
   "SourceVaultCommitmentObserve", "SourceVaultCommitments", 
   "SourceVaultCommitmentSetStatus", "SourceVaultDisableOwnerInputShadow", 
   "SourceVaultEnableOwnerInputShadow", "SourceVaultGuardEvaluate", 
   "SourceVaultGuardRecordParallel", "SourceVaultGuardShadowStats", 
   "SourceVaultHumanSupportProfile", "SourceVaultOperationalSignalEstimate", 
   "SourceVaultOwnerInputRiskAssess", "SourceVaultOwnerInputShadowStats", 
   "SourceVaultOwnerInputShadowStatus", 
   "SourceVaultPlanMessageReleaseWithGuardShadow", 
   "SourceVaultRecordCognitiveSelfReport", "$SourceVaultCognitionEnabled", 
   "$SourceVaultCognitionMinBaselineDays", 
   "$SourceVaultCognitionRetentionDays"}, "SourceVault_comfyui.wl" -> 
  {"SourceVaultComfyUIActivate", "SourceVaultComfyUIAPIAvailable", 
   "SourceVaultComfyUIAPICall", "SourceVaultComfyUIBuildJobSpec", 
   "SourceVaultComfyUIConvertWorkflow", "SourceVaultComfyUIDepositOutputs", 
   "SourceVaultComfyUIFetchOutputs", "SourceVaultComfyUIFetchServerWorkflow", 
   "SourceVaultComfyUIGenerate", "SourceVaultComfyUIGenerateToNotebook", 
   "SourceVaultComfyUIImportServerWorkflow", "SourceVaultComfyUIInterrupt", 
   "SourceVaultComfyUIJobStatus", "SourceVaultComfyUIModels", 
   "SourceVaultComfyUIObjectInfo", "SourceVaultComfyUIPoll", 
   "SourceVaultComfyUIQueue", "SourceVaultComfyUIQueuePrompt", 
   "SourceVaultComfyUIRegisterBackend", "SourceVaultComfyUIRegisterWorkflow", 
   "SourceVaultComfyUIRenderWorkflow", "SourceVaultComfyUIRunWorkflow", 
   "SourceVaultComfyUIServerWorkflows", 
   "SourceVaultComfyUIServerWorkflowsView", "SourceVaultComfyUIStatus", 
   "SourceVaultComfyUISubmitExternal", "SourceVaultComfyUISystemStats", 
   "SourceVaultComfyUIUploadImage", "SourceVaultComfyUIValidateWorkflow", 
   "SourceVaultComfyUIView", "SourceVaultComfyUIWorkflow", 
   "SourceVaultComfyUIWorkflows", "$SourceVaultComfyUIBaseURL", 
   "$SourceVaultComfyUIDefaultProviderName", 
   "$SourceVaultComfyUIDefaultWorkflow", "$SourceVaultComfyUIDepositGrant", 
   "$SourceVaultComfyUIDepositMode", "$SourceVaultComfyUIHTTPHook", 
   "$SourceVaultComfyUIHTTPTimeout", "$SourceVaultComfyUIJobTimeout", 
   "$SourceVaultComfyUIOfflineRecheckSeconds", 
   "$SourceVaultComfyUIStoreRoot"}, "SourceVault_contracts.wl" -> 
  {"SourceVaultAuditFunctionContracts", 
   "SourceVaultCallContractValidatorHook", "SourceVaultContractAliasIndex", 
   "SourceVaultContractFailure", "SourceVaultEnsureInitialized", 
   "SourceVaultExplainCallContract", "SourceVaultFunctionContract", 
   "SourceVaultFunctionContracts", "SourceVaultInitPlan", 
   "SourceVaultNormalizeCallExpression", 
   "SourceVaultRegisterFunctionContract", "SourceVaultRepairCallExpression", 
   "SourceVaultUnregisterFunctionContract", 
   "SourceVaultValidateCallExpression", 
   "SourceVaultValidateFunctionContract", "$SourceVaultInitInProgress"}, 
 "SourceVault_core.wl" -> {"SourceVaultAllocateSnapshotAlias", 
   "SourceVaultAppendEvent", "SourceVaultAtomicUpdatePointer", 
   "SourceVaultBlobRefs", "SourceVaultCanonicalizeForDigest", 
   "SourceVaultCheckVaultConsistency", "SourceVaultCommitBlob", 
   "SourceVaultConcurrentWriteTest", "SourceVaultCoreRoot", 
   "SourceVaultFileStreams", "SourceVaultGCDryRun", 
   "SourceVaultGCGracePeriod", "SourceVaultImmutableSnapshotExistsQ", 
   "SourceVaultLoadImmutableSnapshot", "SourceVaultPointerHistory", 
   "SourceVaultPointerReplay", "SourceVaultRateLimit", "SourceVaultReadBlob", 
   "SourceVaultReadSnapshot", "SourceVaultRecoverLocks", 
   "SourceVaultReleaseFileStreams", "SourceVaultReleaseLock", 
   "SourceVaultResolveArtifactContent", "SourceVaultResolveRoots", 
   "SourceVaultRetentionPlan", "SourceVaultRoot", 
   "SourceVaultRootAssociation", "SourceVaultRootConfigHash", 
   "SourceVaultRunGC", "SourceVaultSaveImmutableSnapshot", 
   "SourceVaultSetImmutableSnapshotPrivacyLevel", "SourceVaultSetRoot", 
   "SourceVaultSnapshotDigest", "SourceVaultSnapshotPrivacyLevel", 
   "SourceVaultSnapshotPrivacyRecord", "SourceVaultStorageDir", 
   "SourceVaultTransactionLog", "SourceVaultTryLock", 
   "SourceVaultVerifyImmutableSnapshot", "SourceVaultWithLock", 
   "$SourceVaultCoreRoot", "$SourceVaultDefaultObjectPrivacyLevel", 
   "$SourceVaultInjectedRootHash", "$SourceVaultInjectedRoots", 
   "$SourceVaultRateLimits"}, "SourceVault_crypto.wl" -> 
  {"SourceVaultAssertNoPlaintextLeak", 
   "SourceVaultAuthorizeRecordMaterialization", "SourceVaultCanonicalBytes", 
   "SourceVaultCanonicalJSONBytes", "SourceVaultConstantTimeEqualQ", 
   "SourceVaultCryptoCapabilityReport", "SourceVaultCryptoSelfTest", 
   "SourceVaultDecryptRecord", "SourceVaultEncryptedGet", 
   "SourceVaultEncryptedPut", "SourceVaultEncryptedRecordQ", 
   "SourceVaultEncryptionKeyStatus", "SourceVaultExportKeyBundle", 
   "SourceVaultHMACSHA256Hex", "SourceVaultImportKeyBundle", 
   "SourceVaultInitializeEncryption", "SourceVaultKeyBundleInfo", 
   "SourceVaultMaterializeRecord", "SourceVaultSealPayload", 
   "SourceVaultUnsealPayload", "$SourceVaultCloudThreshold", 
   "$SourceVaultDefaultAddressBookMACKeyRef", 
   "$SourceVaultDefaultAtRestKeyRef", "$SourceVaultDefaultAtRestMACKeyRef", 
   "$SourceVaultDefaultBaselineMACKeyRef", 
   "$SourceVaultDefaultBaselineSigningKeyRef", 
   "$SourceVaultDefaultCapsuleQuarantineMACKeyRef", 
   "$SourceVaultDefaultMailIdentityHMACKeyRef", 
   "$SourceVaultDefaultPlaintextHMACKeyRef", 
   "$SourceVaultDefaultSelfPrivateKeyRef", 
   "$SourceVaultDefaultSelfSigningKeyRef", 
   "$SourceVaultKeyBundleDefaultPath", "$SourceVaultPrivateThreshold"}, 
 "SourceVault_diagnostics.wl" -> {"SourceVaultDiagnosticsActiveAggregator", 
   "SourceVaultDiagnosticsAggregatorRollup", 
   "SourceVaultDiagnosticsCloudChannel", 
   "SourceVaultDiagnosticsCloudCommsStatus", 
   "SourceVaultDiagnosticsCloudConsume", 
   "SourceVaultDiagnosticsCloudHeartbeat", 
   "SourceVaultDiagnosticsCloudInbox", "SourceVaultDiagnosticsCloudListen", 
   "SourceVaultDiagnosticsCloudPeerLiveness", 
   "SourceVaultDiagnosticsCloudSend", 
   "SourceVaultDiagnosticsCloudStopListen", 
   "SourceVaultDiagnosticsConfigureMail", "SourceVaultDiagnosticsEscalate", 
   "SourceVaultDiagnosticsIngestSpool", 
   "SourceVaultDiagnosticsKernelProcessTopology", 
   "SourceVaultDiagnosticsLicenseProbe", 
   "SourceVaultDiagnosticsLightweightDoctor", 
   "SourceVaultDiagnosticsListProbes", "SourceVaultDiagnosticsLog", 
   "SourceVaultDiagnosticsMachineHeartbeat", 
   "SourceVaultDiagnosticsMachineRegistry", 
   "SourceVaultDiagnosticsMailConfig", "SourceVaultDiagnosticsPanel", 
   "SourceVaultDiagnosticsReadHeartbeats", 
   "SourceVaultDiagnosticsReclaimableCapacity", 
   "SourceVaultDiagnosticsRegisterMachine", 
   "SourceVaultDiagnosticsRegisterProbe", 
   "SourceVaultDiagnosticsSinkAvailableQ", "SourceVaultDiagnosticsStartTick", 
   "SourceVaultDiagnosticsStatus", "SourceVaultDiagnosticsStatusBand", 
   "SourceVaultDiagnosticsStopTick", "SourceVaultDiagnosticsTick", 
   "SourceVaultSystemDoctor", "$SourceVaultDiagIngestIntervalSeconds"}, 
 "SourceVault_eagle.wl" -> {"SourceVaultEagleAddItem", 
   "SourceVaultEagleAddTags", "SourceVaultEagleAPIAvailable", 
   "SourceVaultEagleAPICall", "SourceVaultEagleBuildExifIndex", 
   "SourceVaultEagleCreateFolder", "SourceVaultEagleDataset", 
   "SourceVaultEagleDisableAutoConfidential", 
   "SourceVaultEagleEnableAutoConfidential", "SourceVaultEagleExif", 
   "SourceVaultEagleExtractBibMeta", "SourceVaultEagleExtractBibMetaBatch", 
   "SourceVaultEagleExtractText", "SourceVaultEagleFindFolder", 
   "SourceVaultEagleFolderList", "SourceVaultEagleFolders", 
   "SourceVaultEagleFolderView", "SourceVaultEagleGeoView", 
   "SourceVaultEagleIndexDataset", "SourceVaultEagleIndexRecord", 
   "SourceVaultEagleIndexSearch", "SourceVaultEagleIngest", 
   "SourceVaultEagleIngestFolder", "SourceVaultEagleIngestInfo", 
   "SourceVaultEagleItem", "SourceVaultEagleItemPath", 
   "SourceVaultEagleItems", "SourceVaultEagleItemsInFolder", 
   "SourceVaultEagleLibraries", "SourceVaultEagleLibraryInfo", 
   "SourceVaultEagleLibraryOnlineQ", "SourceVaultEagleMarkViewCells", 
   "SourceVaultEagleMoveToFolder", "SourceVaultEagleOpenItem", 
   "SourceVaultEagleRefresh", "SourceVaultEagleRegisterLibrary", 
   "SourceVaultEagleRemoveTags", "SourceVaultEagleRenameFolder", 
   "SourceVaultEagleSaveCache", "SourceVaultEagleSearch", 
   "SourceVaultEagleSetAnnotation", "SourceVaultEagleSetLibrary", 
   "SourceVaultEagleSetSummaryPrivacy", "SourceVaultEagleSetTags", 
   "SourceVaultEagleSetURL", "SourceVaultEagleShowFolder", 
   "SourceVaultEagleShowInApp", "SourceVaultEagleShowSummary", 
   "SourceVaultEagleSmartFolders", "SourceVaultEagleStatus", 
   "SourceVaultEagleSummaries", "SourceVaultEagleSummarize", 
   "SourceVaultEagleSummarizeBatch", "SourceVaultEagleSummary", 
   "SourceVaultEagleSummaryRow", "SourceVaultEagleTags", 
   "SourceVaultEagleThumbnail", "SourceVaultEagleThumbnailPath", 
   "SourceVaultEagleTrashItem", "SourceVaultEagleUnregisterLibrary", 
   "SourceVaultEagleView", "SourceVaultObjectToCell", 
   "$SourceVaultEagleAPIBase", "$SourceVaultEagleAPIRecheckSeconds", 
   "$SourceVaultEagleAPIToken", "$SourceVaultEagleCacheSaveEvery", 
   "$SourceVaultEagleCloudPublishablePL",
   "$SourceVaultEagleCloudPublishableTag", "$SourceVaultEagleLibrary",
   "$SourceVaultEagleMtimeTTL", "$SourceVaultEagleNotebookStyle", 
   "$SourceVaultEagleOfflineRecheckSeconds", "$SourceVaultEaglePrivacyLevel", 
   "$SourceVaultEagleStoreRoot"}, "SourceVault_identity.wl" -> 
  {"SourceVaultAddressBookFindByEmail", "SourceVaultAddressBookFindByName", 
   "SourceVaultAddressBookGetContact", "SourceVaultAddressBookListContacts", 
   "SourceVaultAddressBookLoad", "SourceVaultAddressBookPutContact", 
   "SourceVaultAddressBookRegisterSelf", "SourceVaultAddressBookSave", 
   "SourceVaultAddressBookStorePath", "SourceVaultFindIdentifier", 
   "SourceVaultGetEntity", "SourceVaultGetIdentifier", 
   "SourceVaultIdentifierCreateEntity", "SourceVaultIdentityBootstrapSelf", 
   "SourceVaultIdentityEnsureLoaded", "SourceVaultIdentityInitialize", 
   "SourceVaultIdentityLoad", "SourceVaultIdentitySave", 
   "SourceVaultIdentityStorePaths", "SourceVaultIngestAddressHeader", 
   "SourceVaultLinkIdentifierToEntity", "SourceVaultListEntities", 
   "SourceVaultListIdentifiers", "SourceVaultObserveIdentifier", 
   "SourceVaultOwnerEmails", "SourceVaultOwnerEntity", 
   "SourceVaultOwnerLLMProfile", "SourceVaultOwnerPrimaryEmail", 
   "SourceVaultParseAuthenticationResults", "SourceVaultPlanMessageRelease", 
   "SourceVaultPutEntity", "SourceVaultRecomputeOwnershipLinks", 
   "SourceVaultResolveIdentifierDisplay", 
   "SourceVaultResolveRecipientProfile", 
   "SourceVaultScheduleOwnershipRefresh", "SourceVaultSenderAuthenticatedQ", 
   "SourceVaultSenderAuthentication", "SourceVaultSenderFeatureUseQ", 
   "SourceVaultSetOwnerLLMProfile", "SourceVaultSetOwnerPrimaryEmail", 
   "SourceVaultTagPolicyEvaluate", "SourceVaultUnlinkIdentifier", 
   "SourceVaultUpdateEntity", "$SourceVaultAddressBookRoot", 
   "$SourceVaultIdentityRoot", "$SourceVaultSystemDenyTags", 
   "$SourceVaultTrustedAuthservIds"}, "SourceVault_knowledgehome.wl" -> 
  {"SourceVaultKnowledgeHomeAppend", 
   "SourceVaultKnowledgeHomeAppendTemplate", 
   "SourceVaultKnowledgeHomeBuildState", 
   "SourceVaultKnowledgeHomeDismissSuggestion", 
   "SourceVaultKnowledgeHomeEnsureLoaded", 
   "SourceVaultKnowledgeHomeExtension", "SourceVaultKnowledgeHomeFollowLink", 
   "SourceVaultKnowledgeHomeMail", "SourceVaultKnowledgeHomeMergeExtensions", 
   "SourceVaultKnowledgeHomeMintItem", 
   "SourceVaultKnowledgeHomeNeighborhoodSearch", 
   "SourceVaultKnowledgeHomeParagraphs", "SourceVaultKnowledgeHomeSearch", 
   "SourceVaultKnowledgeHomeStatus", 
   "SourceVaultKnowledgeHomeSuggestNextNodes", 
   "SourceVaultKnowledgeHomeSuggestView", 
   "SourceVaultKnowledgeHomeSupersede", "SourceVaultKnowledgeHomeTopicField", 
   "SourceVaultKnowledgeHomeTopicPosition", 
   "SourceVaultKnowledgeHomeUndoLast", "SourceVaultKnowledgeHomeView"}, 
 "SourceVault_lexical.wl" -> {"SourceVaultBuildLexicalStats", 
   "SourceVaultBuildSurfaceIndex", "SourceVaultExplainSearchScore", 
   "SourceVaultLexicalRank", "SourceVaultNormalizeSearchText", 
   "SourceVaultSearchTerms"}, "SourceVault_llmlog.wl" -> 
  {"SourceVaultClaudeCodeLogStatus", "SourceVaultClaudeCodeSessionDigest", 
   "SourceVaultClaudeCodeSessionGet", "SourceVaultClaudeCodeSessions", 
   "SourceVaultClaudeCodeSessionSearch", 
   "SourceVaultClaudeCodeSessionSearchView", 
   "SourceVaultClaudeCodeSessionSummary", 
   "SourceVaultClaudeCodeSessionTranscript", 
   "SourceVaultClaudeCodeSessionView", 
   "SourceVaultClaudeCodeSummarizeSessions", 
   "SourceVaultIngestClaudeCodeLogs", "SourceVaultMachineTag", 
   "SourceVaultMirrorClaudeCodeLogs", "SourceVaultRegisterLLMLogMCPAdapter", 
   "$SourceVaultClaudeCodeIngestIntervalSeconds", 
   "$SourceVaultClaudeCodeLogRoots", "$SourceVaultClaudeCodeRawMirrorRoot"}, 
 "SourceVault_mailagenda.wl" -> {"SourceVaultMailAgendaInherit", 
   "SourceVaultMailAgendaItems", "SourceVaultMailAgendaOpen", 
   "SourceVaultMailAgendaReopen", "SourceVaultMailAgendaResolutions", 
   "SourceVaultMailAgendaResolve", "SourceVaultMailForNotebook", 
   "$SourceVaultMailAgendaAddresseePatterns", 
   "$SourceVaultMailAgendaCategories", 
   "$SourceVaultMailAgendaDirectionThreshold", 
   "$SourceVaultMailAgendaEventSink", "$SourceVaultMailAgendaMinPriority", 
   "$SourceVaultMailAgendaOrgAddresses", 
   "$SourceVaultMailAgendaOwnerAddresses", "$SourceVaultMailAgendaWindow"}, 
 "SourceVault_maildb.wl" -> {"SourceVaultAddressBookView", 
   "SourceVaultBackfillMailBodies", "SourceVaultEntityEditUI", 
   "SourceVaultEntityView", "SourceVaultGetMailAccount", 
   "SourceVaultGroupWeightFor", "SourceVaultIdentityBackfillFromMail", 
   "SourceVaultIdentityLinkUI", "SourceVaultImportMaildbFile", 
   "SourceVaultInferMailDerivedBatch", "SourceVaultMailAccounts", 
   "SourceVaultMailAccountsLoad", "SourceVaultMailAddSummaries", 
   "SourceVaultMailAttachmentDir", "SourceVaultMailAttachments", 
   "SourceVaultMailAvailableShards", "SourceVaultMailComposeReply", 
   "SourceVaultMailComputePriority", "SourceVaultMailDataset", 
   "SourceVaultMailDerivedPending", "SourceVaultMailDerivedPendingQ", 
   "SourceVaultMailDisableAutoConfidential", 
   "SourceVaultMailEnableAutoConfidential", "SourceVaultMailEnsureLoaded", 
   "SourceVaultMailExplainPriority", "SourceVaultMailFetchNew", 
   "SourceVaultMailGetBody", "SourceVaultMailIndexedCount", 
   "SourceVaultMailIndexGet", "SourceVaultMailInferDerived", 
   "SourceVaultMailInteractionStats", "SourceVaultMailLoadedCount", 
   "SourceVaultMailLoadShard", "SourceVaultMailMarkViewCells", 
   "SourceVaultMailMigrateToShards", "SourceVaultMailOpenAttachment", 
   "SourceVaultMailOpenReplyNotebook", "SourceVaultMailParseEmails", 
   "SourceVaultMailRebuildMetadataIndex", 
   "SourceVaultMailRecomputePriorities", "SourceVaultMailRowActions", 
   "SourceVaultMailSearchIndex", "SourceVaultMailSearchIndexView", 
   "SourceVaultMailSearchSummary", "SourceVaultMailSend", 
   "SourceVaultMailShardPath", "SourceVaultMailShowBody", 
   "SourceVaultMailSnapshotDecryptBody", "SourceVaultMailSnapshotFromMaildb", 
   "SourceVaultMailSnapshotGet", "SourceVaultMailSnapshotList", 
   "SourceVaultMailSnapshotPut", "SourceVaultMailspecEnrichers", 
   "SourceVaultMailStoreLoad", "SourceVaultMailStorePath", 
   "SourceVaultMailStoreRoot", "SourceVaultMailStoreSave", 
   "SourceVaultMailSummaryRow", "SourceVaultMailThreadNotebook", 
   "SourceVaultMailTranslateBody", "SourceVaultMailUnloadAll", 
   "SourceVaultMailView", "SourceVaultMarkConfidentialViewCells", 
   "SourceVaultPostFetchHooks", "SourceVaultPriorityGroupsLoad", 
   "SourceVaultPriorityGroupWeights", "SourceVaultRegisterMailAccount", 
   "SourceVaultRegisterMailspecEnricher", "SourceVaultRegisterPostFetchHook", 
   "SourceVaultRemoveMailAccount", "SourceVaultSearchMailSnapshots", 
   "SourceVaultSetPriorityGroupWeight", 
   "SourceVaultUnregisterMailspecEnricher", 
   "SourceVaultUnregisterPostFetchHook", "$SourceVaultDefaultImportedMailPL", 
   "$SourceVaultLegacyMailRoot", "$SourceVaultMailAgendaExcludeCacheTTL", 
   "$SourceVaultMailCategories", "$SourceVaultMailConfigRoot", 
   "$SourceVaultMailNotebookStyle", "$SourceVaultMailPersonalPrivacyFloor", 
   "$SourceVaultMailSendBccSelf", "$SourceVaultMailSignature", 
   "$SourceVaultMailStoreRoot", "$SourceVaultMailViewColumnWidths", 
   "$SourceVaultMailViewMaxRows"}, "SourceVault_mailstructure.wl" -> 
  {"SourceVaultBuildMailRelationGraph", "SourceVaultBuildMailTopicGraph", 
   "SourceVaultBuildQuoteFingerprintIndex", 
   "SourceVaultClassifyMailSessionKind", "SourceVaultGrowTopicVocabulary", 
   "SourceVaultLLMProposeTopics", "SourceVaultMailRecordsForStructuring", 
   "SourceVaultMailSnapshotReleaseSource", 
   "SourceVaultMailStructBuildSearchIndex", 
   "SourceVaultMailStructEnsureIndex", 
   "SourceVaultMailStructEnsureReleaseContexts", 
   "SourceVaultMailStructHeaderAvailability", "SourceVaultMailStructSearch", 
   "SourceVaultMailStructSearchThreads", 
   "SourceVaultMailStructSessionChunks", 
   "SourceVaultMailStructSessionDigest", "SourceVaultMailStructSetIndex", 
   "SourceVaultMailStructThread", "SourceVaultMailToGenericRecord", 
   "SourceVaultMineMailSessions", "SourceVaultNewTopicVocabulary", 
   "SourceVaultParseHTMLMailParagraphs", "SourceVaultStructureMail", 
   "SourceVaultTopicVocabularyFromSeed"}, "SourceVault_mailsuggest.wl" -> 
  {"SourceVaultMailReplyDraft", "SourceVaultMailSessionSuggest", 
   "SourceVaultMailSessionSuggestView", "SourceVaultMailThreadPanel", 
   "SourceVaultMailThreadStructure", "SourceVaultMailThreadWindow", 
   "$SourceVaultMailSuggestViewMaxRows"}, "SourceVault_mcp.wl" -> 
  {"SourceVaultBuildURI", "SourceVaultCanonicalURI", 
   "SourceVaultEffectiveAccessLevel", "SourceVaultEstimateOutputPrivacy", 
   "SourceVaultGetModelAccessProfile", "SourceVaultListMCPDataAdapters", 
   "SourceVaultListModelAccessProfiles", "SourceVaultListWorkSessions", 
   "SourceVaultMCPAccessStatus", "SourceVaultMCPApproveAccessRequest", 
   "SourceVaultMCPCallsRecent", "SourceVaultMCPCallTool", 
   "SourceVaultMCPCatalog", "SourceVaultMCPDenyAccessRequest", 
   "SourceVaultMCPDeposit", "SourceVaultMCPDispatch", 
   "SourceVaultMCPEnsureGrantKey", "SourceVaultMCPFeedbackQueue", 
   "SourceVaultMCPGet", "SourceVaultMCPMintAccessGrant", 
   "SourceVaultMCPPendingAccessRequests", "SourceVaultMCPReleaseGate", 
   "SourceVaultMCPRequestAccess", "SourceVaultMCPRevokeAllGrants", 
   "SourceVaultMCPRuntimeCapabilities", "SourceVaultMCPSearch", 
   "SourceVaultMCPServerInfo", "SourceVaultMCPSubmitFeedback", 
   "SourceVaultMCPTools", "SourceVaultMCPVerifyAccessGrant", 
   "SourceVaultMintTraceId", "SourceVaultNormalizeAccessRequest", 
   "SourceVaultNormalizeMCPCallRecord", "SourceVaultNormalizePrincipal", 
   "SourceVaultNormalizeSearchResult", "SourceVaultNormalizeSearchSpec", 
   "SourceVaultObjectData", "SourceVaultObjectPrivacyLevel", 
   "SourceVaultObjectProperties", "SourceVaultObservedReadMax", 
   "SourceVaultPackageCommitLog", "SourceVaultParseURI", 
   "SourceVaultRecordMCPCall", "SourceVaultRegisterMCPDataAdapter", 
   "SourceVaultRenderSearchResults", "SourceVaultResolveAccessProfile", 
   "SourceVaultResolveMCPDataAdapter", 
   "SourceVaultResolvePromptDeliveryProfile", "SourceVaultResolveURI", 
   "SourceVaultSetModelAccessProfile", "SourceVaultStartBatch", 
   "SourceVaultURIForObject", "SourceVaultValidURIQ", 
   "SourceVaultWorkSessionDataset", "SourceVaultWorkSessionGraph", 
   "SourceVaultWorkSessionRecord", "$SourceVaultMCPProtocolVersion", 
   "$SourceVaultURINamespaces"}, "SourceVault_mining.wl" -> 
  {"SourceVaultAddMetacognitiveAssessment", "SourceVaultAssertAuthorship", 
   "SourceVaultAssertTag", "SourceVaultAssessUncertainty", 
   "SourceVaultAuditRecordAddedEvent", "SourceVaultAuthorMatchScore", 
   "SourceVaultAuthorshipObservedEvent", "SourceVaultAwaitJob", 
   "SourceVaultCancelJob", "SourceVaultCheckRetrievalSufficiency", 
   "SourceVaultCommitAssertions", 
   "SourceVaultCompilationConstraintAddedEvent", 
   "SourceVaultDecideEntityLink", "SourceVaultDiagnosticProbeAddedEvent", 
   "SourceVaultEagleRowToAssertions", "SourceVaultEagleTagsToAssertions", 
   "SourceVaultEntityLinkAutoConfirmEligibleQ", 
   "SourceVaultEntityLinkDecisionEvent", "SourceVaultEntityLinkProposals", 
   "SourceVaultEntityLinkProposedEvent", "SourceVaultErrorBookAddedEvent", 
   "SourceVaultErrorBookBlocksAutoConfirmQ", 
   "SourceVaultErrorBookClosedEvent", "SourceVaultErrorBookReopenedEvent", 
   "SourceVaultErrorReopenRate", "SourceVaultExtractAllEagle", 
   "SourceVaultExtractAllMail", "SourceVaultExtractFromEagleRow", 
   "SourceVaultExtractFromMailSnapshot", "SourceVaultExtractFromWebDocument", 
   "SourceVaultExtractWebMetadata", "SourceVaultIterateUntilStable", 
   "SourceVaultJobResult", "SourceVaultJobStatus", 
   "SourceVaultLearnMailDeliveryBaselines", "SourceVaultListMiningJobs", 
   "SourceVaultListPersistedJobs", "SourceVaultLLMExtractAuthors", 
   "SourceVaultLoadMailDeliveryBaselines", "SourceVaultLoadMailGeoCache", 
   "SourceVaultMailDeliveryAnomalyDetectedEvent", 
   "SourceVaultMailDeliveryAnomalyScore", "SourceVaultMailDeliveryBaseline", 
   "SourceVaultMailDeliveryObservation", 
   "SourceVaultMailDeliveryObservationAddedEvent", 
   "SourceVaultMailGeoLookup", "SourceVaultMailHeadersCapturedEvent", 
   "SourceVaultMailMetacognitiveAssessment", "SourceVaultMailToAuthorship", 
   "SourceVaultMakeAuditRecord", "SourceVaultMakeAuthorshipAssertion", 
   "SourceVaultMakeCompilationConstraint", "SourceVaultMakeDiagnosticProbe", 
   "SourceVaultMakeEntityLinkProposal", "SourceVaultMakeErrorBookEntry", 
   "SourceVaultMakeMemoryBranch", "SourceVaultMakeMetacognitiveAssessment", 
   "SourceVaultMakeObjectInteraction", "SourceVaultMakePinnedFact", 
   "SourceVaultMakeProbeRun", "SourceVaultMakeTagAssertion", 
   "SourceVaultMemoryBranchOpenedEvent", "SourceVaultMemoryVitalityScore", 
   "SourceVaultMetacognitiveAssessmentEvent", 
   "SourceVaultMetacognitiveAssessmentToMiningObject", 
   "SourceVaultMetacognitiveBlocksAutoConfirmQ", 
   "SourceVaultMetacognitiveFaithfulnessScore", "SourceVaultMinedSearch", 
   "SourceVaultMiningAuthorshipFetchHook", "SourceVaultMiningBoost", 
   "SourceVaultMiningMailHeaderObservation", 
   "SourceVaultMiningMetacognitiveEnricher", 
   "SourceVaultMiningObjectAddedEvent", "SourceVaultMiningRerank", 
   "SourceVaultMiningSafetyEnricher", 
   "SourceVaultMiningUnwireProductionHooks", 
   "SourceVaultMiningWebIngestAssertions", 
   "SourceVaultMiningWebIngestExtract", "SourceVaultMiningWebIngestHook", 
   "SourceVaultMiningWireProductionHooks", "SourceVaultObjectAuthorships", 
   "SourceVaultObjectImportanceSetEvent", 
   "SourceVaultObjectInteractionRecordedEvent", "SourceVaultObjectTags", 
   "SourceVaultOpenErrorBookEntries", "SourceVaultParseMailHeaders", 
   "SourceVaultPersistJob", "SourceVaultPinnedFactAddedEvent", 
   "SourceVaultPinnedFactToConstraint", "SourceVaultProbePassRate", 
   "SourceVaultProbeRunRecordedEvent", "SourceVaultProbeRunToPinnedFact", 
   "SourceVaultProposeEntityLink", "SourceVaultQueryLocalLLM", 
   "SourceVaultReasoningRetrieve", "SourceVaultReplayEntityLinkProposals", 
   "SourceVaultReplayErrorBook", "SourceVaultReplayMetacognitiveAssessments", 
   "SourceVaultReplayObjectSignals", "SourceVaultReplayTagAssertions", 
   "SourceVaultRestoreJobs", "SourceVaultRunIdentityTagMining", 
   "SourceVaultRunMiningPipeline", "SourceVaultRunWikiCompileRefine", 
   "SourceVaultSafetyQuarantinedQ", "SourceVaultSaveMailDeliveryBaselines", 
   "SourceVaultSaveMailGeoCache", "SourceVaultSecurityPreScan", 
   "SourceVaultSetMailDeliveryBaseline", 
   "SourceVaultSubmitReasoningRetrieve", 
   "SourceVaultSubmitWikiCompileRefine", "SourceVaultTagAssertionEvent", 
   "SourceVaultTagAssertionSupersededEvent", "SourceVaultTagDecisionEvent", 
   "SourceVaultTagMatchScore", "SourceVaultUncertaintyDiscrimination", 
   "SourceVaultWebDocumentToAssertions", 
   "SourceVaultWebMetadataToAuthorship", "SourceVaultWebTopicTags", 
   "$SourceVaultLocalLLMKey", "$SourceVaultMailDeliveryBaselineFn", 
   "$SourceVaultMailGeoFn", "$SourceVaultMiningJobDir", 
   "$SourceVaultMiningProductionHooksEnabled"}, 
 "SourceVault_oopsseed.wl" -> {"SourceVaultAssignParagraphTopics", 
   "SourceVaultBuildMailChunks", "SourceVaultBuildMailQuoteEdges", 
   "SourceVaultBuildMailSessions", "SourceVaultBuildOOPSRelationGraph", 
   "SourceVaultBuildSeedEntityDictionary", "SourceVaultBuildSessionChunks", 
   "SourceVaultBuildSessionDigest", "SourceVaultBuildSessionPrimerItems", 
   "SourceVaultBuildTopicItemGraph", "SourceVaultConfirmCandidateTopics", 
   "SourceVaultExpandSearchGraph", "SourceVaultExpandTopicsByRelation", 
   "SourceVaultExtractCandidateTopics", "SourceVaultExtractExplicitTopics", 
   "SourceVaultExtractMailQuoteMarkers", "SourceVaultImportOOPSItemNames", 
   "SourceVaultImportOOPSItemRelations", "SourceVaultImportOOPSMailInfo", 
   "SourceVaultImportOOPSMailToItem", "SourceVaultImportOOPSQuoteTable", 
   "SourceVaultImportOOPSSeedDictionary", "SourceVaultLoadExtractedTopics", 
   "SourceVaultMailRecipientPrivacy", "SourceVaultOOPSEnsureLoaded", 
   "SourceVaultOOPSSearchThreads", "SourceVaultOOPSSessions", 
   "SourceVaultOOPSStatus", "SourceVaultOOPSThread", 
   "SourceVaultOOPSThreadGraph", "SourceVaultOOPSThreadList", 
   "SourceVaultOOPSThreadView", "SourceVaultOOPSTopicGraphPlot", 
   "SourceVaultParseMailParagraphs", "SourceVaultParseOOPSMailFile", 
   "SourceVaultReadSExprString", "SourceVaultSaveExtractedTopics", 
   "SourceVaultSeedDictionaryStats", "SourceVaultStripOOPSMarkers", 
   "SourceVaultTopicEnrichment"}, "SourceVault_packageapi.wl" -> 
  {"SourceVaultPackageApiChunks", "SourceVaultPackageApiGet", 
   "SourceVaultPackageApiIndexBuild", "SourceVaultPackageApiIndexStatus", 
   "SourceVaultPackageApiRelated", "SourceVaultPackageApiResolve", 
   "SourceVaultPackageApiSearch", "$SourceVaultPackageApiPackages"}, 
 "SourceVault_privacy.wl" -> {"SourceVaultDeclareModulePrivacy", 
   "SourceVaultDeclarePrivacySource", "SourceVaultEvaluationPrivacy", 
   "SourceVaultMarkEvaluationPrivacyCells", 
   "SourceVaultModulePrivacyDeclarations", "SourceVaultNotePrivacy", 
   "SourceVaultNotePrivacyOf", "SourceVaultPendingPrivacyMarks", 
   "SourceVaultPrivacyAudit", "SourceVaultPrivacyCallGraph", 
   "SourceVaultPrivacyConformanceTest", "SourceVaultPrivacyContract", 
   "SourceVaultPrivacyContracts", "SourceVaultPrivacyLevelOf", 
   "SourceVaultPrivacyProbes", "SourceVaultPrivacyReachesSource", 
   "SourceVaultPrivacyReviewedSymbols", "SourceVaultPrivacySources", 
   "SourceVaultPrivacyUnwrap", "SourceVaultPrivacyWriteReview", 
   "SourceVaultPrivate", "SourceVaultPrivateResult", 
   "SourceVaultPrivateView", "SourceVaultRegisterPrivacyContract", 
   "SourceVaultRegisterPrivacyProbe", "SourceVaultResetEvaluationPrivacy", 
   "SourceVaultWithPrivacyScope", "Sym", "Symbol", 
   "$SourceVaultPrivacyDefaultLevel", "$SourceVaultPrivacyMarkThreshold", 
   "$SourceVaultPrivacyViewBadge"}, "SourceVault_promptrouter.wl" -> 
  {"AddPromptMemo", "SaveLastPrompt", "SourceVaultAddSavedPrompt", 
   "SourceVaultAutoSaveLastPrompt", "SourceVaultCallableAllowlistRegistry", 
   "SourceVaultCallableAllowlistView", "SourceVaultCaptureLastPromptRun", 
   "SourceVaultClassifyPromptContextDependency", 
   "SourceVaultClassifyPromptReplaySafety", 
   "SourceVaultClassifyProviderTrustDomain", "SourceVaultDecryptPromptRoute", 
   "SourceVaultDeletePromptRoute", "SourceVaultExecutePromptRoute", 
   "SourceVaultFormatPromptRouteList", "SourceVaultGetPromptRoute", 
   "SourceVaultListPromptRoutes", "SourceVaultMatchSavedPromptVersions", 
   "SourceVaultPrimaryPromptRoute", "SourceVaultPromotePromptRun", 
   "SourceVaultPromptPrivacyAllowsCloudRouter", 
   "SourceVaultPromptReprocessPlan", "SourceVaultPromptRoutePanel", 
   "SourceVaultPromptRouterActiveQ", "SourceVaultPromptRouterAvailableQ", 
   "SourceVaultPromptRouterStatus", "SourceVaultPromptRunHistory", 
   "SourceVaultPromptRunRecord", "SourceVaultPromptVersionsUI", 
   "SourceVaultProposePromptRoute", "SourceVaultProposeSavedPromptRoute", 
   "SourceVaultRegisterPromptRoute", "SourceVaultReplayRoute", 
   "SourceVaultResolveModelForPromptRouter", 
   "SourceVaultResolvePromptPrivacy", "SourceVaultResolvePromptRoute", 
   "SourceVaultRouteExplain", "SourceVaultRunPrimaryRoute", 
   "SourceVaultSearchPromptRoutes", "SourceVaultSetPrimaryPromptRoute", 
   "SourceVaultUpdatePromptRouteMemo", "$SourceVaultPromptAutoSave", 
   "$SourceVaultPromptBypassOnce", "$SourceVaultPromptPanelMaxRows", 
   "$SourceVaultPromptRouterVersion", 
   "$SourceVaultPromptSavedProposalActive"}, "SourceVault_routineplan.wl" -> 
  {"SourceVaultRoutineAgendaData", "SourceVaultRoutineAgendaView", 
   "SourceVaultRoutineDayCapacityFn", 
   "SourceVaultRoutineDefaultCapacityModel", 
   "SourceVaultRoutineFabricCapacityFn", "SourceVaultRoutineFabricTasks", 
   "SourceVaultRoutineFocusRequest", "SourceVaultRoutineGanttData", 
   "SourceVaultRoutineGanttView", "SourceVaultRoutineLatestSafeStart", 
   "SourceVaultRoutineLoadData", "SourceVaultRoutineLoadView", 
   "SourceVaultRoutinePlacePlan", "SourceVaultRoutinePreparationTasks", 
   "SourceVaultRoutineProcessGraph", "SourceVaultRoutineReplan", 
   "SourceVaultRoutineSlack"}, "SourceVault_routine.wl" -> 
  {"SourceVaultRoutineActionClass", "SourceVaultRoutineActionGate", 
   "SourceVaultRoutineApplyDurable", "SourceVaultRoutineApproveAutomation", 
   "SourceVaultRoutineAttentionGate", "SourceVaultRoutineAttentionPolicy", 
   "SourceVaultRoutineAutomationEligibility", 
   "SourceVaultRoutineAutomationProposals", "SourceVaultRoutineBoardData", 
   "SourceVaultRoutineBoardView", "SourceVaultRoutineBuildOccurrence", 
   "SourceVaultRoutineCoverageDegradedQ", 
   "SourceVaultRoutineDefaultAttentionPolicy", 
   "SourceVaultRoutineEnqueueNotification", 
   "SourceVaultRoutineEvaluateEvidence", 
   "SourceVaultRoutineExecutionStreams", "SourceVaultRoutineFormulaicScore", 
   "SourceVaultRoutineFreshness", 
   "SourceVaultRoutineFulfillmentCacheRebuild", 
   "SourceVaultRoutineFulfillmentReached", "SourceVaultRoutineIdentity", 
   "SourceVaultRoutineInQuietHours", "SourceVaultRoutineKeyString", 
   "SourceVaultRoutineKleeneAllOf", "SourceVaultRoutineKleeneAnyOf", 
   "SourceVaultRoutineKleeneNot", "SourceVaultRoutineLedgerAppend", 
   "SourceVaultRoutineLedgerEvents", "SourceVaultRoutineLedgerReplay", 
   "SourceVaultRoutineLedgerWatermark", 
   "SourceVaultRoutineMandatoryLadderStage", "SourceVaultRoutineNextDue", 
   "SourceVaultRoutineNotificationEnvelope", 
   "SourceVaultRoutineOverdueSeconds", 
   "SourceVaultRoutineOverdueSecondsByDay", "SourceVaultRoutineOwnerMachine", 
   "SourceVaultRoutineProposeAutomation", "SourceVaultRoutineQualityRank", 
   "SourceVaultRoutineQueueRecords", "SourceVaultRoutineQueueReset", 
   "SourceVaultRoutineQueueTick", "SourceVaultRoutineRecertificationClass", 
   "SourceVaultRoutineRejectAutomation", "SourceVaultRoutineResolveSeries", 
   "SourceVaultRoutineSetAttentionPolicy", 
   "SourceVaultRoutineSetOwnerMachine", "SourceVaultRoutineStaleUsePolicy", 
   "SourceVaultRoutineSupersedeNotifications", 
   "SourceVaultRoutineTemporalState", "SourceVaultRoutineTickGuard", 
   "SourceVaultRoutineTriple", "$SourceVaultRoutineCacheRoot", 
   "$SourceVaultRoutineLedgerRoot", "$SourceVaultRoutineThisMachineTag"}, 
 "SourceVault_searchindex.wl" -> {"SourceVaultAnswerForInteraction", 
   "SourceVaultAppendMultimodalEvent", "SourceVaultBuildIndexSnapshot", 
   "SourceVaultBuildMediaIndex", "SourceVaultBuildPrimerIndex", 
   "SourceVaultBuildProjectionIndex", "SourceVaultBuildPurposeIndex", 
   "SourceVaultBuildRealtimeContext", "SourceVaultBuildRevocationSet", 
   "SourceVaultClassifyQuestionTPO", "SourceVaultClearRegistry", 
   "SourceVaultCompactRevocationTombstone", "SourceVaultCorpusSnapshotInfo", 
   "SourceVaultDiffCorpusSnapshots", "SourceVaultEmbeddingProvider", 
   "SourceVaultEmbedTexts", "SourceVaultEvaluateReleasePolicy", 
   "SourceVaultEvaluateSearch", "SourceVaultEvaluateTPOGate", 
   "SourceVaultFreezeCorpusSnapshot", "SourceVaultHybridSearch", 
   "SourceVaultIndexSearcher", "SourceVaultIndexSnapshotInfo", 
   "SourceVaultListEmbeddingProviders", "SourceVaultListProfiles", 
   "SourceVaultListReleaseContexts", "SourceVaultListRetrievalWorkflowKinds", 
   "SourceVaultListSearchGroups", "SourceVaultListSearchIndexes", 
   "SourceVaultListTPOProfiles", "SourceVaultLoadPrimerIndex", 
   "SourceVaultLoadRetrievalWorkflowSnapshot", "SourceVaultLoadSearchIndex", 
   "SourceVaultLoadSearchProfiles", "SourceVaultMediaPrivacyDefault", 
   "SourceVaultObjectRevocationStatus", 
   "SourceVaultPDFIndexLegacyResultToSearchResult", 
   "SourceVaultPDFIndexLegacySearch", "SourceVaultPDFIndexMigrationReport", 
   "SourceVaultPreviewPDFIndexMigration", "SourceVaultPrimerSearch", 
   "SourceVaultRegisterEmbeddingProvider", 
   "SourceVaultRegisterHTTPEmbeddingProvider", 
   "SourceVaultRegisterOCRBackend", 
   "SourceVaultRegisterPDFIndexMigrationRule", 
   "SourceVaultRegisterPDFIndexProfile", "SourceVaultRegisterReleaseContext", 
   "SourceVaultRegisterRetrievalWorkflowKind", 
   "SourceVaultRegisterSearchBackend", "SourceVaultRegisterSearchGroup", 
   "SourceVaultRegisterSearchIndexProfile", "SourceVaultRegisterTPOProfile", 
   "SourceVaultReleaseContextSpec", "SourceVaultReloadSearchIndex", 
   "SourceVaultResolveOCRBackend", "SourceVaultResolvePDFIndexProfile", 
   "SourceVaultResolveSearchBackend", "SourceVaultResolveSearchIndexProfile", 
   "SourceVaultRevocationEpoch", "SourceVaultRevokeObject", 
   "SourceVaultSaveRetrievalWorkflowSnapshot", 
   "SourceVaultSaveSearchProfiles", "SourceVaultSearch", 
   "SourceVaultSearchGroupSpec", "SourceVaultSearchIndexStatus", 
   "SourceVaultSessionEvents", "SourceVaultSetEmbeddingProvider", 
   "SourceVaultTPOProfile", "SourceVaultUnloadSearchIndex", 
   "SourceVaultValidateIndexSnapshot", "SourceVaultValidateTPOProfile", 
   "$SourceVaultEmbeddingDim", "$SourceVaultPDFIndexAutoLoad", 
   "$SourceVaultPDFIndexLoader", "$SourceVaultPDFLegacySearchFunction", 
   "$SourceVaultPersistSearchProfiles"}, "SourceVault_searchview.wl" -> 
  {"SourceVaultAgenticSearch", "SourceVaultAppendGraphAnnotation", 
   "SourceVaultApplySearchContextProfile", 
   "SourceVaultBuildInteractionMetaGraph", 
   "SourceVaultBuildRetrievalEpisodeGraph", "SourceVaultBuildSearchView", 
   "SourceVaultCascadeSearch", "SourceVaultClassifyQueryComplexity", 
   "SourceVaultCloseRetrievalEpisode", "SourceVaultEpisodeInfluenceScores", 
   "SourceVaultExplainSearchContext", "SourceVaultFollowSearchViewLink", 
   "SourceVaultRecordSearchAttempt", "SourceVaultRecordTopicItemInteraction", 
   "SourceVaultRegisterSearchContextProfile", 
   "SourceVaultRenderSearchNotebookView", "SourceVaultSearchEpisodeMemory", 
   "SourceVaultSelectSearchContextProfile", 
   "SourceVaultStartRetrievalEpisode"}, "SourceVault_servicemanager.wl" -> 
  {"SourceVaultActivateServiceVersion", "SourceVaultActiveServiceVersion", 
   "SourceVaultAnswerChannelQuery", "SourceVaultAskLiveSession", 
   "SourceVaultClearServiceRegistry", "SourceVaultCompareServiceVersions", 
   "SourceVaultCreateServiceVersionSnapshot", "SourceVaultDispatchOutput", 
   "SourceVaultEvaluateActionGate", "SourceVaultEvaluateOutputGate", 
   "SourceVaultGetLiveEvents", "SourceVaultGetLiveSummary", 
   "SourceVaultGetLiveTranscript", "SourceVaultHTTPProxyStatus", 
   "SourceVaultIngestCapturedMedia", "SourceVaultInstallWatchdog", 
   "SourceVaultListCaptureSources", "SourceVaultListMultimodalWorkflows", 
   "SourceVaultListRuntimeMachines", "SourceVaultListServiceProfiles", 
   "SourceVaultListServices", "SourceVaultListServiceVersions", 
   "SourceVaultLoadLocalInit", "SourceVaultLocalConfigDoctor", 
   "SourceVaultLocalConfigRoot", "SourceVaultLocalConfigStatus", 
   "SourceVaultMakeActionDraft", "SourceVaultMakeMailReplyDraft", 
   "SourceVaultMakeQuestionEnvelope", "SourceVaultMaterializeProxyCode", 
   "SourceVaultMCPRunningQ", "SourceVaultMCPStatus", 
   "SourceVaultNoPersonalConfigDoctor", "SourceVaultProxyRuntimeDir", 
   "SourceVaultPublishProxyCodeSnapshot", "SourceVaultRecoverServices", 
   "SourceVaultRegisterCapabilityProfile", 
   "SourceVaultRegisterCaptureSource", "SourceVaultRegisterChannelEndpoint", 
   "SourceVaultRegisterLLMBackend", "SourceVaultRegisterMultimodalWorkflow", 
   "SourceVaultRegisterOutputAdapter", "SourceVaultRegisterVoiceBackend", 
   "SourceVaultRegisterVRSNSAdapter", 
   "SourceVaultRegisterWebServiceEndpoint", 
   "SourceVaultResolveServiceProfile", 
   "SourceVaultResolveWebServiceEndpoint", "SourceVaultRestartService", 
   "SourceVaultRollbackServiceVersion", "SourceVaultSchedulePostprocess", 
   "SourceVaultSendServiceCommand", "SourceVaultServiceCommandResult", 
   "SourceVaultServiceDoctor", "SourceVaultServiceHealth", 
   "SourceVaultServiceHealthDetail", "SourceVaultServiceLogs", 
   "SourceVaultServiceMain", "SourceVaultServicePing", 
   "SourceVaultServiceRootHealth", "SourceVaultServiceRuntimeDir", 
   "SourceVaultServiceStatus", "SourceVaultServiceVersionInfo", 
   "SourceVaultStartHTTPProxy", "SourceVaultStartMCP", 
   "SourceVaultStartService", "SourceVaultStopHTTPProxy", 
   "SourceVaultStopMCP", "SourceVaultStopService", 
   "SourceVaultTailServiceLog", "SourceVaultTestCaptureSource", 
   "SourceVaultUninstallWatchdog", "SourceVaultUpdateLiveSummary", 
   "SourceVaultWatchdogStatus", "$SourceVaultHealthRequireL2", 
   "$SourceVaultHealthThresholds", "$SourceVaultMCPPort", 
   "$SourceVaultMCPServiceId", "$SourceVaultMCPToken", "$SourceVaultPython", 
   "$SourceVaultServiceWLMCPEnabled", 
   "$SourceVaultStreamSweepIntervalSeconds"}, 
 "SourceVault_simrun.wl" -> {"SourceVaultCUDACompile", 
   "SourceVaultCUDARequire", "SourceVaultGPUAvailableQ", 
   "SourceVaultMachineProfile", "SourceVaultMachineProfileRefresh", 
   "SourceVaultMachineSpecs", "SourceVaultMachineSpecsText", 
   "SourceVaultMachineSpecsView", "SourceVaultNvccPath", 
   "SourceVaultSimRunCreate", "SourceVaultSimRunFinalize", 
   "SourceVaultSimRunFolder", "SourceVaultSimRunRecord", 
   "SourceVaultSimRunRoot", "SourceVaultSimRuns", 
   "SourceVaultSubkernelTarget", "SourceVaultWithSubkernels", 
   "$SourceVaultSimRunRoot", "$SourceVaultSubkernelMax"}, 
 "SourceVault_taint.wl" -> {"SourceVaultAssessInputTrust", 
   "SourceVaultComposeCrossObjectRisk", "SourceVaultPropagateTaint", 
   "SourceVaultRunIntegrityState", "SourceVaultTaintDeclassify", 
   "SourceVaultTaintEdgeCarriesContentQ", 
   "SourceVaultTransitionRunIntegrity"}, "SourceVault_webingest.wl" -> 
  {"SourceVaultAddReferenceEvent", "SourceVaultDerivedArtifact", 
   "SourceVaultDerivedArtifactList", "SourceVaultDerivedArtifactsForSource", 
   "SourceVaultPruneRolledReferenceEvents", "SourceVaultRecordImportance", 
   "SourceVaultRefCount", "SourceVaultReferenceEventStoreStatus", 
   "SourceVaultRegisterWebIngestHook", "SourceVaultRollupReferenceEvents", 
   "SourceVaultSaveDerivedArtifact", "SourceVaultSearXNGAvailableQ", 
   "SourceVaultSearXNGSearch", "SourceVaultSetWebDomainWeight", 
   "SourceVaultStoreSummaryToken", "SourceVaultSummarizeResults", 
   "SourceVaultSummarizeText", "SourceVaultSwapWebSearchBackend", 
   "SourceVaultUnregisterWebIngestHook", "SourceVaultWebComputePriority", 
   "SourceVaultWebDomainWeightFor", "SourceVaultWebDomainWeights", 
   "SourceVaultWebDomainWeightsLoad", "SourceVaultWebFetch", 
   "SourceVaultWebHighlights", "SourceVaultWebImportance", 
   "SourceVaultWebIngestHooks", "SourceVaultWebJobList", 
   "SourceVaultWebJobResult", "SourceVaultWebJobStatus", 
   "SourceVaultWebPriority", "SourceVaultWebRecomputePriorities", 
   "SourceVaultWebRecoverStaleJobs", "SourceVaultWebSearch", 
   "SourceVaultWebSearchIntegration", "SourceVaultWebSearchRunList", 
   "SourceVaultWebSearchSubmit", "SourceVaultWrapUntrustedText", 
   "$SourceVaultExaFallbackIntegrationId", "$SourceVaultRefEventWeights", 
   "$SourceVaultRollupIntervalSeconds", "$SourceVaultSearXNGEndpoint", 
   "$SourceVaultSummaryEndpoint", "$SourceVaultSummaryModel", 
   "$SourceVaultSummaryToken", "$SourceVaultWebSearchAsync", 
   "$SourceVaultWebSearchIntegrationId"}, "SourceVault_wiring.wl" -> 
  {"SourceVaultApplyAdapterPath", "SourceVaultBindingFromFile", 
   "SourceVaultBindingFromURI", "SourceVaultBindingFromValue", 
   "SourceVaultBindingFromVariable", "SourceVaultBindingPrivacyMax", 
   "SourceVaultCellInput", "SourceVaultCellOutput", 
   "SourceVaultCoerceFromURI", "SourceVaultCoerceToURI", 
   "SourceVaultCollectWorkflowInput", "SourceVaultConfidentialContextQ", 
   "SourceVaultCreateInputBundle", "SourceVaultExecuteWiringPlan", 
   "SourceVaultFillUnresolvedWithLLM", "SourceVaultFindAdapterPath", 
   "SourceVaultMakeValueEnvelope", "SourceVaultNormalizeURIEnvelope", 
   "SourceVaultPortAdapters", "SourceVaultPortBindingRefQ", 
   "SourceVaultProposeWiringPlan", "SourceVaultRegisterPortAdapter", 
   "SourceVaultRegisterWiringWorkflow", "SourceVaultRunWorkflow", 
   "SourceVaultSelectFunctionsForTask", "SourceVaultSubmitWorkflowInput", 
   "SourceVaultURIEnvelopeQ", "SourceVaultValidateWiringPlan", 
   "SourceVaultValidateWorkflowInput", "SourceVaultValueEnvelopeQ", 
   "SourceVaultWiringPlanExpression", "$SourceVaultConfidentialPrivacyLevel", 
   "$SourceVaultWiringLLM"}, "SourceVault.wl" -> 
  {"ClaudeResolveModel", "MaxCharacters", "PinVersion", "PrivacyLabel", 
   "SourceVaultArXiv", "SourceVaultAssignClaudeModels", "SourceVaultAttach", 
   "SourceVaultAttachToCell", "SourceVaultBackfillArXivSummaries", 
   "SourceVaultBundleCreate", "SourceVaultBundleDelete", 
   "SourceVaultBundleGet", "SourceVaultBundleInvalidate", 
   "SourceVaultBundleList", "SourceVaultBundlesForSnapshot", 
   "SourceVaultBundleStatus", "SourceVaultClaim", 
   "SourceVaultClaimsForSource", "SourceVaultClaimsForTopic", 
   "SourceVaultClaimStoreCompact", "SourceVaultClaimStoreStatus", 
   "SourceVaultClaudeAttachIntegrationDisable", 
   "SourceVaultClaudeAttachIntegrationEnable", 
   "SourceVaultClaudeAttachIntegrationStatus", 
   "SourceVaultClaudeAttachmentsIntegrationDisable", 
   "SourceVaultClaudeAttachmentsIntegrationEnable", 
   "SourceVaultClaudeAttachmentsIntegrationStatus", 
   "SourceVaultClearModelRegistry", "SourceVaultCompileRegistry", 
   "SourceVaultContext", "SourceVaultContextAssemble", 
   "SourceVaultCurrentDirectiveSnapshot", "SourceVaultDetectLocalModels", 
   "SourceVaultDiffDirectiveSnapshots", "SourceVaultDiffVersions", 
   "SourceVaultDirectiveRepositoryStatus", 
   "SourceVaultDirectiveSnapshotStaleQ", "SourceVaultEnsureNotebookUUID", 
   "SourceVaultEnsureNotebookUUIDFolder", "SourceVaultEnsureRegistered", 
   "SourceVaultExtract", "SourceVaultExtractNotebookHeader", 
   "SourceVaultExtractNotebookTaggingRules", 
   "SourceVaultExtractNotebookTodos", "SourceVaultExtractPages", 
   "SourceVaultFindNotebooks", "SourceVaultFindTodos", 
   "SourceVaultFormatNotebookList", "SourceVaultGetAttachments", 
   "SourceVaultGetCellSources", "SourceVaultGetClaudeAttachRefs", 
   "SourceVaultGetNotebookSummary", "SourceVaultGetSchema", 
   "SourceVaultHarnessRuntimeEnvironmentChangedQ", 
   "SourceVaultIndexDirectiveRepository", "SourceVaultIndexNotebook", 
   "SourceVaultIndexNotebookFolder", "SourceVaultIngest", 
   "SourceVaultIngestWait", "SourceVaultInitialize", "SourceVaultList", 
   "SourceVaultListModels", "SourceVaultListRegistries", 
   "SourceVaultListSchemas", "SourceVaultLookup", 
   "SourceVaultMarkSnapshotInvalidated", "SourceVaultMarkSnapshotStale", 
   "SourceVaultMarkTodo", "SourceVaultMaterializeForSink", 
   "SourceVaultModelContextLength", "SourceVaultModelEndpointStatus", 
   "SourceVaultModelIntegrations", "SourceVaultModelIntentMap", 
   "SourceVaultNewNotebook", "SourceVaultNotebookLint", 
   "SourceVaultNotebookSemanticHash", "SourceVaultNotebookSummary", 
   "SourceVaultNotebookSummaryStatus", "SourceVaultNotebookUUID", 
   "SourceVaultObjectSpec", "SourceVaultOCRDisable", "SourceVaultOCREnable", 
   "SourceVaultOCRStatus", "SourceVaultOpenSourceFile", 
   "SourceVaultParseProposalIntegrationDisable", 
   "SourceVaultParseProposalIntegrationEnable", 
   "SourceVaultParseProposalIntegrationStatus", 
   "SourceVaultReclassifyPublicPrivacy", "SourceVaultRefreshAllSummaries", 
   "SourceVaultRefreshModelRegistry", "SourceVaultRefreshSnapshot", 
   "SourceVaultRegisterDirectiveRepository", 
   "SourceVaultRegisterHarnessMaterialization", 
   "SourceVaultRegisterNotebook", "SourceVaultRegisterNotebookSummary", 
   "SourceVaultRegisterSchema", "SourceVaultRegisterSeed", 
   "SourceVaultRegisterSummaryProvider", "SourceVaultRegistryStatus", 
   "SourceVaultRelinkSources", "SourceVaultResetStore", "SourceVaultResolve", 
   "SourceVaultResolvePath", "SourceVaultResolveReference", 
   "SourceVaultSelectSources", "SourceVaultSetModel", 
   "SourceVaultSetModelIntent", "SourceVaultSetSnapshotPrivacyLevel", 
   "SourceVaultShowSourceSummary", "SourceVaultSnapshots", 
   "SourceVaultSourceEventAppend", "SourceVaultSourceEvents", 
   "SourceVaultSourceRow", "SourceVaultSources", "SourceVaultSpan", 
   "SourceVaultStatus", "SourceVaultSummaries", "SourceVaultSync", 
   "SourceVaultSyncPlan", "SourceVaultSyncStatus", 
   "SourceVaultUpcomingSchedule", 
   "SourceVaultWorkerPromptIntegrationDisable", 
   "SourceVaultWorkerPromptIntegrationEnable", 
   "SourceVaultWorkerPromptIntegrationStatus", "Topic", "TrustLevel", 
   "$SourceVaultCloudRootAliases", "$SourceVaultCloudRoots", 
   "$SourceVaultDefaultNotebookFolder", "$SourceVaultMaxFileSizeMB", 
   "$SourceVaultModelEndpoints", "$SourceVaultOCRHook", 
   "$SourceVaultOCRMode", "$SourceVaultOCRVerbose", "$SourceVaultRoots", 
   "$SourceVaultSeedModelRegistry", "$SourceVaultSummaryNotebookStyle", 
   "$SourceVaultSummaryProviders", "$SourceVaultVersion", 
   "$SourceVaultWorkerPromptAutoDetect"}, "SourceVault_workflowcatalog.wl" -> 
  {"SourceVaultDemoteWorkflow", "SourceVaultMigrateWorkflowsToStages", 
   "SourceVaultOpenSourceNotebook", "SourceVaultPromoteWorkflow", 
   "SourceVaultRegisterSourceNotebook", "SourceVaultRegisterWorkflowCatalog", 
   "SourceVaultSetWorkflowStatus", "SourceVaultSourceNotebookPath", 
   "SourceVaultWorkflowArchivePanel", "SourceVaultWorkflowCatalog", 
   "SourceVaultWorkflowCatalogRecord", "SourceVaultWorkflowPanel", 
   "SourceVaultWorkflowStatus", "SourceVaultWorkflowSummarize", 
   "SourceVaultWorkflowSummarizeText"}, "SourceVault_workflowregistry.wl" -> 
  {"SourceVaultLoadWorkflow", "SourceVaultRunWorkflowAsync", 
   "SourceVaultRunWorkflowAsyncJobs", "SourceVaultRunWorkflowChild", 
   "SourceVaultRunWorkflowResult", "SourceVaultWorkflowContext", 
   "SourceVaultWorkflowDirectory", "SourceVaultWorkflowFolder", 
   "SourceVaultWorkflows", "SourceVaultWorkflowStageDirectory", 
   "$SourceVaultWorkflowStages"}|>
